### ISSUE TITLE
Pulse excite

### ISSUE THREAD

**Issue by r9y9** [r9y9/pysptk#11]
https://twitter.com/piyo56_net/status/639877394883461120

**Comment by r9y9** [comment]
https://github.com/shunsukeaihara/pysas has `excite` module, which provides pulse excitation generation . Close this.

**Comment by jfsantos** [comment]
Don't you think pysptk should support the excitation generator from SPTK as well? pysas does not seem to use the same method from SPTK, and the excitations generated by both methods seem to be different.
