### ISSUE TITLE
compilation error?

### ISSUE THREAD

**Issue by tam17aki** [r9y9/pysptk#16]
I tried to install pysptk, but unfortunately got the following error.

The whole messages is here;
https://gist.github.com/tam17aki/b67d374ed094997d07dc

Best regards,
Akira

---------------------------------

duplicate symbol _ppade in:

    build/temp.macosx-10.9-x86_64-2.7/lib/SPTK/bin/lmadf/_lmadf.o

    build/temp.macosx-10.9-x86_64-2.7/lib/SPTK/bin/mlsadf/_mlsadf.o

ld: 1 duplicate symbol for architecture x86_64

clang: error: linker command failed with exit code 1 (use -v to see invocation)

error: command 'clang' failed with exit status 1

**Comment by tam17aki** [comment]
This may be because 'double *ppade;' in both _lmadf.c and _mlsadf.c ...?

**Comment by r9y9** [comment]
Thanks you for reporting the problem. I haven't reproduce it yet, duplicate symbols should definitely be fixed. For reference, could you please tell me what version of clang, OSX and cython you are using?

**Comment by r9y9** [comment]
I was able to reproduce the problem. The `-fno-common` option seems to cause this failure. I will try to fix  duplicate symbols, anyway.

**Comment by r9y9** [comment]
This should be fixed in https://github.com/r9y9/SPTK (and original SPTK as well?)

**Comment by tam17aki** [comment]
clang:
Apple LLVM version 6.0 (clang-600.0.57) (based on LLVM 3.5svn)
Target: x86_64-apple-darwin13.4.0
Thread model: posix

OSX:
10.9.5 Yosemite

cython:
Cython version 0.23.1

I think SPTK still contains latent bugs ...

Best regards,
Akira

**Comment by r9y9** [comment]
I think this should be fixed now. Please try the latest version:

```
pip install git+https://github.com/r9y9/pysptk
```

**Comment by tam17aki** [comment]
pysptk was successfully installed.

Thanks,
Akira

**Comment by r9y9** [comment]
Thank you!

**Comment by r9y9** [comment]
Released v0.1.2, which includes the fix for #16. More change logs are found at https://github.com/r9y9/pysptk/blob/master/NEWS.md#v012.
