### ISSUE TITLE
Installation guide

### ISSUE THREAD

**Issue by r9y9** [r9y9/pysptk#17]
There is some dependency that must be satisfied before installing by pip. For example, I had to install `python-pip`, `python-dev` and `python-numpy` in a clean ubuntu 14.04 (in vagrant). I should note some installation guide.

**Comment by r9y9** [comment]
A few instructions are added. I think adding platform-specific guides are very helpful but it's not an important task, since pysptk should be easily installed by simpliy `pip install pysptk`.

**Comment by r9y9** [comment]
ref #25

**Comment by r9y9** [comment]
Windows specific guide was added, so I think it's enough. Close this

**Comment by ABC0408** [comment]
When I try install pysptk in Ubuntu 16.04, Anancoda 3.6.7 met this error:

> /home/leyuan/anaconda3/compiler_compat/ld: cannot find -lpthread
  /home/leyuan/anaconda3/compiler_compat/ld: cannot find -lc
  collect2: error: ld returned 1 exit status
  error: command 'gcc' failed with exit status 1

And I also found the reason: [This is an Anaconda issue](https://github.com/cocodataset/cocoapi/issues/94#issuecomment-350152998), but after I used the source added **extra_link_args=['-L/usr/lib/x86_64-linux-gnu/']** to setup.py **ext_modules**, and then run **python setup.py install**, another error came:

> leyuan@Eden:~/pysptk$ python setup.py install
running install
running bdist_egg
running egg_info
writing pysptk.egg-info/PKG-INFO
writing dependency_links to pysptk.egg-info/dependency_links.txt
writing requirements to pysptk.egg-info/requires.txt
writing top-level names to pysptk.egg-info/top_level.txt
reading manifest file 'pysptk.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching '*.c' under directory 'lib'
warning: no files found matching '*.h' under directory 'lib'
warning: no files found matching 'COPYING' under directory 'lib'
writing manifest file 'pysptk.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
-- Building version 0.1.15+61cb932
copying pysptk/version.py -> build/lib.linux-x86_64-3.6/pysptk
running build_ext
skipping 'pysptk/_sptk.c' Cython extension (up-to-date)
building 'pysptk._sptk' extension
gcc -pthread -B /home/leyuan/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/leyuan/anaconda3/lib/python3.6/site-packages/numpy/core/include -I/home/leyuan/pysptk/lib/SPTK/include -I/home/leyuan/anaconda3/include/python3.6m -c pysptk/_sptk.c -o build/temp.linux-x86_64-3.6/pysptk/_sptk.o -std=c99
pysptk/_sptk.c:565:18: fatal error: SPTK.h: don't has that file or dictionary
 #include "SPTK.h"
                  ^
compilation terminated.
error: command 'gcc' failed with exit status 1

But I used pip install pysptk successfully, without anaconda environment. 
Can you help me install it with anaconda environment.
