### ISSUE TITLE
Add support to the RAPT pitch extraction algorithm

### ISSUE THREAD

**Issue by jfsantos** [r9y9/pysptk#30]
I would like to use RAPT as the pitch extraction algorithm as in my (limited) experience it has slightly better performance than SWIPE'. Could you describe the required steps to add it? I can implement it myself and send a pull request.

**Comment by r9y9** [comment]
I assume you have already found steps to support RAPT :).

Actually, I tried to expose the RAPT interface in SPTK one or two years ago, but I gave up to do that since the code was too complicated, I thought. Pull request is really welcome!

**Comment by jfsantos** [comment]
I still have not managed to wrap it. The code is *really* weird and dependant on using a linked list instead of an array as input. I might try to tackle this soon, but as I could not waste much time on this I implemented an ugly wrapper which simply pipes data in and out to the SPTK `pitch` binary.

**Comment by r9y9** [comment]
Good news: I refactored the RAPT code a bit and probably was able to warp RAPT with a simple interface which takes input as an array instead of a linked list. I'm going to write a regression test to ensure my fixes don't do anything wrong.

**Comment by jfsantos** [comment]
This is great! Unfortunately I did not have time to help you review it, but I'm sure you did a great job. I will check this out this week to help test it.
