### ISSUE TITLE
FFT length not equal to original SPTK code

### ISSUE THREAD

**Issue by robotnc** [r9y9/pysptk#38]
I am using pysptk with World vocoder, and found that when using the mcep() function, the FFT length parameter is not same compare with the original C code.

In Pysptk the fft_length = len(windowed_data), but in C code we can input a fft_length directly.

In my case my data is 513 length ,and fft_length should be 1024, I try to modify the code for fft_length =(len(window)-1)*2, the function is ok, but the pysptk got Segmentation fault:11 frequenctly.

Can you fixed it as same as the original SPTK?

**Comment by r9y9** [comment]
FIxed as same as the C code [here](https://github.com/r9y9/SPTK/blob/2a4abfeaddfdaf464c14779bae5d334d769c656a/bin/mcep/mcep.c#L245-L248). Please reopen if it doesn't fix your issue.
