### ISSUE TITLE
Can I remove hold music from an audio using this?

### ISSUE THREAD

**Issue by StanSilas** [r9y9/pysptk#51]
Hello, Is there any way to clean up audio files so that I can remove the hold music parts from an audio so that the final audio has just the speech parts?

**Comment by r9y9** [comment]
http://librosa.github.io/librosa/generated/librosa.effects.trim.html#librosa.effects.trim might be what you are looking for.

**Comment by r9y9** [comment]
This is out of scope. Closing.
