### ISSUE TITLE
questions about function mc2sp in conversion.py

### ISSUE THREAD

**Issue by attitudechunfeng** [r9y9/pysptk#52]
hi, @r9y9. I have questions about function mc2sp in conversion.py when reading your codes. the parameter 'mc' passed into 'mc2sp' is a 2d array, and i tested that 'c' returned by 'freqt' is also a 2d array. But, 'symc' declared in this function is a 1d array as 'symc=np.zeros(fftlen)', and is it wrong about the code 'symc[0] = c[0]'?

**Comment by r9y9** [comment]
This is correct. If you pass a 2d array input, then function decorated with `apply_along_last_axis` (e.g., `freqt` and `mc2sp`) is applied along with the last axis, taking input as 1d array.

**Comment by attitudechunfeng** [comment]
thank u!  I have also noticed that~

**Comment by attitudechunfeng** [comment]
And do you know what "cdef double[:, ::1]" mean in cython? i'm not familiar with cython.

**Comment by r9y9** [comment]
C-contiguous typed memoryviews. See http://cython.readthedocs.io/en/latest/src/userguide/memoryviews.html#c-and-fortran-contiguous-memoryviews for details.

**Comment by attitudechunfeng** [comment]
thanks!
