### ISSUE TITLE
versions with sptk

### ISSUE THREAD

**Issue by Shellbye** [r9y9/pysptk#61]
In sptk, the help msg show like before,
```bash
freqt -h

 freqt - frequency transformation

  usage:
       freqt [ options ] [ infile ] > stdout
  options:
       -m m  : order of minimum phase sequence      [25]
       -M M  : order of warped sequence             [25]
       -a a  : all-pass constant of input sequence  [0]
       -A A  : all-pass constant of output sequence [0.35]
       -h    : print this message
  infile:
       minimum phase sequence (float)               [stdin]
  stdout:
       warped sequence (float)

 SPTK: version 3.11
 CVS Info: $Id$
```
But in pysptk, there is only two parameter(order=25, alpha=0.0), I wonder what's the difference, is it because of the version?

I'm really green hand, i'm sorry for the silly question if it is.

**Comment by Shellbye** [comment]
I asked someone else, turn out that python does not need some param since numpy has them.

**Comment by r9y9** [comment]
Yes, I wanted to simplify API as possible. One more important difference is that `alpha` should be specified as a relative value, as oppose to the SPTK CLI. For example,

- SPTK: a=0, A=0.35, Python: alpha=0.35
- SPTK: a=0.35, A=0, Python: alpha=-0.35

I hope this helps you understand.

**Comment by Shellbye** [comment]
I haven't noticed the difference of `alpha`, thank you for your notice.
