### ISSUE TITLE
Continuous integration build fails because numpy is missing.

### ISSUE THREAD

**Issue by lorenzocestaro** [r9y9/pysptk#65]
Hi @r9y9,

I am building building a project  which has `pysptk` as a dependency and my builds are failing because the `setup.py` script requires `numpy` as a dependency.

For my CI, I can use an easy workaround and install `numpy` previous to running my project's `pip install`. Anyway this could create problems for production builds (e.g. docker) and usability problems in general.

I think this could be easily fixed using the `setup_requires` in your `setup.py`. Search for `setup_requires` [here](https://setuptools.readthedocs.io/en/latest/setuptools.html).

I am willing to look into this and eventually submit a PR if you want.

**Comment by r9y9** [comment]
Hi, thank you for the suggestion. That sounds good to me. Could you send a PR for it?

**Comment by lorenzocestaro** [comment]
Ok, so I looked into this and it appears that `setup_requires` is incompatible with pip right now and the problem of the missing numpy installation is unavoidable when building from source.
See also [this discussion](https://github.com/scikit-learn/scikit-learn/issues/7867) for the exact same issue on scikit-learn.

What is avoidable, though, is having end users unable to install the package if they do not have numpy in their environment. This can be fixed by publishing a wheel instead of a source bundle (or both) when releasing new versions: 
- `python setup.py sdist` forces end users to build from source and raises an error if numpy is missing. - `python setup.py bdist_wheel` will produce a pip wheel that takes care of installing all dependencies under `install_requires` and wil not produce errors for end users when `pip install pysptk` is run.

You can build and upload to pypi both of them with `python setup.py sdist bdist_wheel`.

Hope I've been clear.

**Comment by r9y9** [comment]
I used to provide wheels for earlier releases (e.g., see https://pypi.org/project/pysptk/0.1.3/#files), but as far as I remember correctly there's a binary compatibility issue(s) for linux and also I didn't want  to create wheels for each python/os environments, so I end up with the source distribution. I hope there's a clean and simple solution to this.

**Comment by r9y9** [comment]
I've tagged a new release v0.1.15. I believe this should fix the issue. For double-check, @lorenzocestaro Could you please confirm if it works?

**Comment by r9y9** [comment]
Thanks! If you provide me code to reproduce the test failures, I can take a look. Let me know if you need a help.

**Comment by r9y9** [comment]
I'm closing this out. Feel free to reopen if the problem persists.
