### ISSUE TITLE
pysptk setup error

### ISSUE THREAD

**Issue by superhg2012** [r9y9/pysptk#68]
Hi, when pull code from github and install manually by `python setup.py  build` an error occured

`running build
running build_py
-- Building version 0.1.15+71b73cc
copying pysptk/version.py -> build/lib.linux-x86_64-3.6/pysptk
running build_ext
skipping 'pysptk/_sptk.c' Cython extension (up-to-date)
building 'pysptk._sptk' extension
gcc -pthread -B /opt/anaconda3-5.1.0/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/opt/anaconda3-5.1.0/lib/python3.6/site-packages/numpy/core/include -I/root/pysptk/lib/SPTK/include -I/opt/anaconda3-5.1.0/include/python3.6m -c pysptk/_sptk.c -o build/temp.linux-x86_64-3.6/pysptk/_sptk.o -std=c99
pysptk/_sptk.c:523:18: fatal error: SPTK.h: No such file or directory
compilation terminated.
error: command 'gcc' failed with exit status 1`

so, how to slove this?

**Comment by superhg2012** [comment]
@r9y9 could you help to see it?

**Comment by r9y9** [comment]
Try `git submodule update --init` for building from source. The C library is included as a submodule.

For building from source, please see the guide as well https://pysptk.readthedocs.io/en/latest/development.html#how-to-build-pysptk:

```
git clone https://github.com/r9y9/pysptk
cd pysptk
git submodule update --init
python setup.py develop
```

**Comment by superhg2012** [comment]
> Try git submodule update --init for building from source. The C library is included as a submodule.
> For building from source, please see the guide as well https://pysptk.readthedocs.io/en/latest/development.html#how-to-build-pysptk:
> git clone https://github.com/r9y9/pysptk
> cd pysptk
> git submodule update --init
> python setup.py develop

thanks！！problem solved!!
