### ISSUE TITLE
mgcep with itype != 0

### ISSUE THREAD

**Issue by b-schnell** [r9y9/pysptk#72]
Hello r9y9,

Thanks a lot for making this repo. I have the following problem: I am extracting the amplitude spectrum with some other program and like to use the mgcep function to turn amplitude spectrum into MGCs. However, the `windowed_length`, which determines the fft size and has to be a power of 2, is taken from the input array, which causes the following error:
> fft : m must be a integer of power of 2!

https://github.com/r9y9/pysptk/blob/af944406ad54d2e5561fdcde49900892363479f9/pysptk/_sptk.pyx#L152
Taking the size from the input directly is only correct for the input of a windowed signal (`itype==0`), for all others, I think, it should be `(len(windowed) - 1) * 2`, probably the same as in the mcep function:
https://github.com/r9y9/pysptk/blob/af944406ad54d2e5561fdcde49900892363479f9/pysptk/_sptk.pyx#L106

It would be great if you can take a look at it. Thanks!

Best

**Comment by r9y9** [comment]
Thank you for raising this. I will look into it when I find the time.

**Comment by r9y9** [comment]
I made a PR #73 to fix this. Could you check if it works?

**Comment by r9y9** [comment]
Feel free to reopen if the problem persists.

**Comment by b-schnell** [comment]
I tested the mgcep function and it seems to work. Thanks a lot for the quick fix.

**Comment by r9y9** [comment]
Thanks!!
