### ISSUE TITLE
difference between pysptk.sp2mc AND pyworld.code_spectral_envelope

### ISSUE THREAD

**Issue by tttyhelper** [r9y9/pysptk#74]
Hello. Thank you for this good library.
I thought pysptk.sp2mc is equivalent to pyworld.code_spectral_envelope.
But they yield different values.

What is difference between them ?

**Comment by r9y9** [comment]
Could you check the code? If there’s anything unclear, I’d happy to elaborate on it.

**Comment by tttyhelper** [comment]
I just wanna transform spectral envelope into mcep. I found two library and their functions.
pysptk.sp2mc and pyworld.code_spectral_envelope. But they make different outputs. So i don't know which one to choose...

**Comment by r9y9** [comment]
`pysptk.sp2mc` converts spectral envelope to *mel-cepstrum* (see https://pdfs.semanticscholar.org/b219/461c2ab15ce476b27b2062da3d904132c395.pdf for details).  The primary difference is that `pysptk.sp2mc` is designed so that the output will be the parameters of a speech synthesis filter, while WORLD's method is not.

**Comment by tttyhelper** [comment]
Thank you very much.

**Comment by tttyhelper** [comment]
Thank you sir, I have one more question. Your paper uses term mel-cepstral coefficient which appears as MCEP or MCC in other papers. But in pysptk documentation, it defines MCEP as mel-cepstrum. Are mel-cepstral coefficient and mel-cepstrum same? Your answer would be a lot of help.. Thank you

**Comment by r9y9** [comment]
Sounds they are same (as I can only tell from the names), but not exactly sure since I don't know what exactly you are talking about :(

>  Your paper uses term mel-cepstral coefficient which appears as MCEP or MCC in other papers. 

What paper are you talking about? I don't remember writing a paper and using the term mel-cepstral coefficient... For more details about mel-cepstrum, please read the paper as I mentioned above, and SPTK (NOT pysptk)'s documentation as well.

**Comment by tttyhelper** [comment]
Oh I meant the paper you linked above [https://pdfs.semanticscholar.org/b219/461c2ab15ce476b27b2062da3d904132c395.pdf](https://pdfs.semanticscholar.org/b219/461c2ab15ce476b27b2062da3d904132c395.pdf)

And MCEP or MCC (both referring mel-cepstral coefficient) appear in papers such as 
https://arxiv.org/pdf/1907.12279.pdf (as MCEP)
https://arxiv.org/pdf/1808.05092.pdf (as MCC)

Thank you ! I will read the docs. If you know difference between MCEP/MCC and mel-cepstrum (I think they are same too.), please let me know :)

**Comment by r9y9** [comment]
Oh I see. Thank you for the references. I consider those are SAME. Both papers use WORLD as  a vocoder. 

An example of extracting mel-cepstrum (MCEP, MCC, or something else) by WORLD can be found at https://github.com/k2kobayashi/sprocket/blob/4f1408ac487e046a502a6ca416a06955d5cb4a71/sprocket/speech/feature_extractor.py#L121-L139, which may be helpful for you.

**Comment by tttyhelper** [comment]
Thanks. You saved my life... Arigato

**Comment by r9y9** [comment]
https://kunzhou9646.github.io/Odyssey2020_emotional_VC/

https://github.com/KunZhou9646/Nonparallel-emotional-VC/blob/8355dc68c24af9fcda15e090780005b96c56d69f/Parallel-data-free%20emotional%20voice%20conversion%20with%20CycleGAN%20and%20CWT/preprocess.py#L27-L34 They use WORLD's method. I think both are fine.

**Comment by tttyhelper** [comment]
Thank you very much.
I was trying to get `MCD(mel-cepstral disortion)` that appears as equation (8) in the [paper](https://arxiv.org/abs/2002.00198) you linked.
But I got different values from pysptk and pyworld with same equation.
I'm not sure if WORLD's `coded_sps` is `MCEP`, since only evidence of it is that author of this [Repo](https://github.com/leimao/Voice_Converter_CycleGAN/blob/master/preprocess.py) called `coded_sps` as `MCEP`.
And the github you linked also seems forked from this repo (has same preprocess.py).
I will check inside both libraries `sptk` and `world` for confirm. Thank you !
