### ISSUE TITLE
RAPT is giving all zeros

### ISSUE THREAD

**Issue by pabloriera** [r9y9/pysptk#85]
I am passing some audios to both pitch functions, and while swipe gives a result, rapt is always zeros
```
f0 = pysptk.rapt(input_audio.astype(np.float32), fs=sr, hopsize=80, min=60, max=300, otype="f0")
f0 = pysptk.swipe(input_audio.astype(np.float64), fs=sr, hopsize=80, min=60, max=300, otype="f0")
```

Thanks

**Comment by tebin** [comment]
I had the same problem, fixed it by multiplying the audio by 32767. Honestly they should change the function to accept int16 not float32, because when it says float32 most people assume it's the normalized version i.e. between -1.0 and 1.0.
