### ISSUE TITLE
About MCEP Function

### ISSUE THREAD

**Issue by chankl3579** [r9y9/pysptk#88]
Thanks for the repo and sorry for asking a dump question. 
I am trying to use the ```mcep``` function in the package for calculating Mel Cepstral Distortion. 
According to your online document, the input to this function is ```windowed```, which is descripted as "a windowed frame with shape (frame length)". 
I am not sure what actually this frame is. Is there another function in the package that calculate this frame from an audio file? 
Or what is the recommended way to get this frame?
Thanks.

**Comment by r9y9** [comment]
https://pysptk.readthedocs.io/en/latest/sptk.html#window-functions

Please also check the example notebook: https://nbviewer.org/github/r9y9/pysptk/blob/master/examples/pysptk%20introduction.ipynb
